version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ecommerce-net

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ecommerce-net

  postgres:
    image: postgres:16
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  pgdata:
